# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

encoding: utf-8
port: 3000
host: 0.0.0.0

permalink: /:title.html

title: Linux & Python & C
email: 582223837@qq.com
description: > # this means to ignore newlines until "baseurl:"
    linux和python方面有关的技术总结
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.pythonwood.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pythonwood
github_username:  pythonwood
oldblog_url:    http://www.cnblogs.com/weishun

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

